### ISSUE TITLE
Error: while adding dependancy

### ISSUE THREAD

**Issue by expertdev-designer** [breadwallet/breadwallet-android#162]
Dependency verification failed for configuration ':app-core:kotlinCompilerClasspath'
One artifact failed verification: circleimageview-3.1.0.pom (de.hdodenhof:circleimageview:3.1.0) from repository MavenRepo
If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/6.6/userguide/dependency_verification.html#sec:troubleshooting-verification

Open this report for more details: file:///Users/admin/Desktop/AndroidProjects/breadwallet-android/build/reports/dependency-verification/at-1600690392221/dependency-verification-report.html

**Comment by DrewCarlson** [comment]
This error is produced by the Gradle [Dependency Verification](https://docs.gradle.org/6.6/userguide/dependency_verification.html) feature.

If you've added a new dependency run `./gradlew --write-verification-metadata sha256,pgp --export-keys` to generate the metadata entries.  Otherwise please detail what you're trying to do and I may be able to help.

**Comment by expertdev-designer** [comment]
@DrewCarlson Thanks!
It's working fine.

> This error is produced by the Gradle [Dependency Verification](https://docs.gradle.org/6.6/userguide/dependency_verification.html) feature.
> 
> If you've added a new dependency run `./gradlew --write-verification-metadata sha256,pgp --export-keys` to generate the metadata entries. Otherwise please detail what you're trying to do and I may be able to help.
