### ISSUE TITLE
Error when rebuild

### ISSUE THREAD

**Issue by ywj7931** [breadwallet/breadwallet-android#40]
_peerManager = BRPeerManagerNew(_wallet, (uint32_t) earliestKeyTime, _blocks,
                                        (size_t) blocksCount,
                                        _peers, (size_t) peersCount);

Error:(296, 68) error: too few arguments to function call, expected 7, have 6

**Comment by Gutyn** [comment]
Hi, this will be fixed in the next public release to GitHub. Today or tomorrow. Apologies. 
What happened to you is the core was updated (due to a line in grade that does that on every build) but the java side not. If you need it working urgently feel free to downgrade the Breadwallet-core by one commit.
