### ISSUE TITLE
Backend API

### ISSUE THREAD

**Issue by benitech** [breadwallet/breadwallet-android#42]
@Gutyn @voisine @samuraisam 

Guys, i love your work. And would love to carry it forward for our own use case but without access to your backend API being opensource as well, building our own by checking stetho becomes a generally tough task.

While not impossible, it would just be a waste of resources for others in the dev community who are forking breadwallet (103 forks so far) to have to build their own backend APIs.

I have checked most of the forked projects and they all seem to be using "api.breadwallet.com" and "stage2.breadwallet.com" as their primary backend API source. So while this might be great, but one of your comments that even if "breadwallet" company did not exist anymore, people could still use their wallets fully. I don't think that would work out OK.

Just asking you to opensource your backend API as well, if possible.

Thanks. And Great work once again.

**Comment by voisine** [comment]
The only api that's really needed for a functioning wallet is exchange rates and fee rates. Since these are something that can be determined using the SPV p2p protocol, our next best option is to provide a public api for them ourselves, and then have the app fail over to one or more other public apis if ours is unavailable. Right now only the fee rate is missing this fail over functionality (although it does cache the previous result locally and use that if it's not too old). The fee rate fail over is on our list and should be in the app soon.
